version: '3.9'

services:
  cassandra_db:
    image: 'cassandra:latest'
    container_name: chat_service_db
    ports:
      - 9042:9042
    volumes:
      - /Users/ajaysankaran/Desktop/code/db/cassandra:/var/lib/cassandra
  
  redis:
    image: 'redis/redis-stack'
    container_name: chat_service_redis
    ports:
      - 6379:6379
    volumes:
      - /Users/ajaysankaran/Desktop/code/db/redis:/root/redis
  

networks:
  redis:
    driver: bridge

