version: '3.9'

services:

  db:
    image: 'postgres:latest'
    container_name: chat_app_db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - /Users/ajaysankaran/Desktop/code/db/postgres/chat_app:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: chat_app
      POSTGRES_DB: chat_app
      POSTGRES_PASSWORD: chat@1234

  